# Generated by Django 3.2.18 on 2023-04-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('xbox', models.URLField(blank=True)),
                ('playstation', models.URLField(blank=True)),
                ('steam', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitch', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_profile_l8giye', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
