# Generated by Django 3.2.18 on 2023-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='../default_event_t6y6sk', upload_to='images/'),
        ),
    ]
