# Generated by Django 3.2.18 on 2023-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
