# Generated by Django 3.2.18 on 2023-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(default='123456', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='../default_event_ixlmh0', upload_to='images/'),
        ),
    ]
