# Generated by Django 3.2.18 on 2023-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230420_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default='123456'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
