# Generated by Django 3.2.18 on 2023-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20230425_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
