# Generated by Django 3.2.18 on 2023-04-20 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20230417_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='Hi', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'post')},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
    ]
