# Generated by Django 3.2.18 on 2023-04-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('likes', '0002_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_likes', to='events.event'),
        ),
    ]
