# Generated by Django 3.2.18 on 2023-04-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('likes', '0002_auto_20230412_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_likes', to='events.event'),
        ),
    ]
