# Generated by Django 3.2.18 on 2023-04-20 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0003_alter_like_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'post')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='event',
        ),
    ]
