# Generated by Django 3.2.18 on 2023-04-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20230408_1742'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_response', to='chats.chat'),
        ),
    ]
