# Generated by Django 3.2.18 on 2023-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='content',
        ),
        migrations.AddField(
            model_name='poll',
            name='response',
            field=models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], default='yes', max_length=255),
        ),
    ]
