# Generated by Django 3.2.18 on 2023-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20230421_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='response',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='Do you like this?', max_length=255),
        ),
    ]
