# Generated by Django 3.2.18 on 2023-04-08 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20230408_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chattee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chattee', to=settings.AUTH_USER_MODEL),
        ),
    ]
