# Generated by Django 3.2.18 on 2023-04-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20230408_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
    ]
