# Generated by Django 3.2.18 on 2023-04-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20230408_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chattee',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
