# Generated by Django 3.2.18 on 2023-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='phone',
            field=models.IntegerField(blank=True, default=1234),
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
