# Generated by Django 3.2.18 on 2023-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20230418_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
