# Generated by Django 3.2.18 on 2023-04-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='events.event'),
        ),
    ]
