# Generated by Django 3.2.18 on 2023-04-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230420_1712'),
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='event',
            field=models.ForeignKey(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], on_delete=django.db.models.deletion.CASCADE, related_name='event_replies', to='events.event'),
        ),
    ]
