# Generated by Django 3.2.18 on 2023-04-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230420_1712'),
        ('replies', '0002_alter_reply_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='events.event'),
        ),
    ]
